name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install SLURM
      run: sudo apt-get install libslurm-dev
    - uses: actions/checkout@v2
    - name: make
      run: make
